version: 2
jobs: 
  build: 
   working_directory: ~/ksashikumar/fd-spaces-node
   docker: 
      - image: "circleci/node:7.10" 
      - image: "circleci/mysql:5.6"
        environment:
           MYSQL_USER: ubuntu
           MYSQL_PASSWORD: ""
           MYSQL_DB: circle_test
   steps: 
      - checkout
      - restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - run: 
          command: "npm install && npm install mysql && sudo npm install mocha && npm install sql-fixtures"
          name: "Install Dependencies"
      - run: 
          command: "sudo npm install nodeunit -g && sudo npm install -g db-migrate-mysql && sudo npm install -g migration && sudo npm install -g db-migrate && db-migrate create meeting && db-migrate up && node fixture.js"
          name: "Nodeunit here && db"
      - save_cache: 
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - run: 
          name: "Unit testing"
          command: "cd .. && cd test/unit && nodeunit unittest.js"
      - run: 
          name: "Integration testing"
          command: "cd .. && cd integration && npm run test-integration"
          
