version: 2
jobs: 
  build: 
   working_directory: ~/ksashikumar/fd-spaces-node
   docker: 
      -  image: "circleci/node:7.10"
      -  image: "circleci/mysql:5.6"
   environment:
      DATABASE_URL: "mysql://root:@127.0.0.1:3306/circle_test"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root 
      MYSQL_DB: circle_test
   steps: 
      - checkout
      - restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - run: 
          command: "npm install && npm install mysql && sudo npm install mocha"
          name: "Install Dependencies"
      - run: 
          command: "sudo npm install nodeunit -g && sudo npm install -g db-migrate-mysql && sudo npm install -g migration && sudo npm install -g db-migrate && db-migrate create meeting && db-migrate up && node fixture.js"
          name: "Nodeunit here && db"
      - save_cache: 
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - run: 
          command: "cd .. && cd test/unit && nodeunit unittest.js"
          name: "Unit testing"
      - run: 
          command: "cd .. && cd integration && npm run test-integration"
          name: "Integration testing"
